let data=[{name:"RajeshKumar",
            batch:"B45WD",
            gender:"Male",
            qualification:"BSC"},
            {name:"LogeshKumar",
            batch:"B45WD",
            gender:"Male",
            qualification:"BCA"},
            {name:"Anitha",
            batch:"B45WD",
            gender:"Female",
            qualification:"B.Com"},
            {name:"Prabhu",
            batch:"B45WD",
            gender:"Male",
            qualification:"BSC"},
            {name:"Soosana",
            batch:"B45WD",
            gender:"Female",
            qualification:"BBA"}]
            
export default data;